"""Add locked status to cards and more user settings

Revision ID: b36479f22106
Revises: 67f6a5e0e8cb
Create Date: 2026-01-29 13:53:20.566921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b36479f22106'
down_revision: Union[str, Sequence[str], None] = '67f6a5e0e8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card",
        sa.Column(
            "locked",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        )
    )
    op.add_column('usersettings', sa.Column('add_cards_to_collection_after_trade', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersettings', 'add_cards_to_collection_after_trade')
    op.drop_column('card', 'locked')
    # ### end Alembic commands ###
